### ISSUE TITLE
How Can I Establish An SSL Connection With A Database Using Gino

### ISSUE THREAD

**Issue by mashaalmemon** [fantix/gino#202]
* GINO version: 0.7.0
* Python version: 3.6
* Operating System: MacOSX

### Description

How can I make an SSL Connection with Gino? Is this possible? 

### What I Did

Couldn't find an example of this in documentation or in issues.

**Comment by mashaalmemon** [comment]
Great i’ll try that and confirm if I am successful. Stay tuned.

**Comment by fantix** [comment]
Tested in Travis, anyway please feel free to let me know if you have further issues with this.

**Comment by ppsirg** [comment]
i found a problem on one of our production servers with tornado, python code is here:

```!python
# database setup
current.run_sync(
    lambda: db.init_app(app, ssl=False, **DB_INFO)
    )
```

and error log is:

```
[trng@as]$ python -OO app.py 
/usr/local/python/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
{'host': 'lol.com', 'port': 5432, 'database': 'lol', 'user': 'vl', 'password': 'llll'}
Traceback (most recent call last):
  File "app.py", line 80, in <module>
    main()
  File "app.py", line 62, in main
    lambda: db.init_app(app, ssl=True, **DB_INFO)
  File "/usr/local/python/lib/python3.6/site-packages/tornado/ioloop.py", line 576, in run_sync
    return future_cell[0].result()
  File "/usr/local/python/lib/python3.6/site-packages/gino/ext/tornado.py", line 246, in init_app
    ssl=ssl, loop=asyncio_loop,
  File "/usr/local/python/lib/python3.6/site-packages/gino/ext/tornado.py", line 200, in set_bind
    return await super().set_bind(bind, loop=loop, **kwargs)
  File "/usr/local/python/lib/python3.6/site-packages/gino/api.py", line 390, in set_bind
    bind = await create_engine(bind, loop=loop, **kwargs)
  File "/usr/local/python/lib/python3.6/site-packages/gino/strategies.py", line 42, in create
    pool = await dialect.init_pool(u, loop)
  File "/usr/local/python/lib/python3.6/site-packages/gino/dialects/asyncpg.py", line 328, in init_pool
    **self._pool_kwargs)
  File "/usr/local/python/lib/python3.6/site-packages/gino/dialects/asyncpg.py", line 213, in _init
    self._pool = await asyncpg.create_pool(**args)
  File "/usr/local/python/lib/python3.6/site-packages/asyncpg/pool.py", line 398, in _async__init__
    await self._initialize()
  File "/usr/local/python/lib/python3.6/site-packages/asyncpg/pool.py", line 415, in _initialize
    await first_ch.connect()
  File "/usr/local/python/lib/python3.6/site-packages/asyncpg/pool.py", line 125, in connect
    self._con = await self._pool._get_new_connection()
  File "/usr/local/python/lib/python3.6/site-packages/asyncpg/pool.py", line 461, in _get_new_connection
    **self._connect_kwargs)
  File "/usr/local/python/lib/python3.6/site-packages/asyncpg/connection.py", line 1688, in connect
    max_cacheable_statement_size=max_cacheable_statement_size)
  File "/usr/local/python/lib/python3.6/site-packages/asyncpg/connect_utils.py", line 551, in _connect
    raise last_error
  File "/usr/local/python/lib/python3.6/site-packages/asyncpg/connect_utils.py", line 543, in _connect
    connection_class=connection_class)
  File "/usr/local/python/lib/python3.6/site-packages/asyncpg/connect_utils.py", line 513, in _connect_addr
    connector, timeout=timeout, loop=loop)
  File "/usr/local/python/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/python/lib/python3.6/site-packages/asyncpg/connect_utils.py", line 606, in _create_ssl_connection
    ssl_is_advisory=ssl_is_advisory)
  File "/usr/local/python/lib/python3.6/site-packages/asyncpg/connect_utils.py", line 592, in _negotiate_ssl_connection
    return await conn_factory(sock=sock)  # Must come after tr.close()
  File "/usr/local/python/lib/python3.6/asyncio/base_events.py", line 804, in create_connection
    sock, protocol_factory, ssl, server_hostname)
  File "/usr/local/python/lib/python3.6/asyncio/base_events.py", line 830, in _create_connection_transport
    yield from waiter
  File "/usr/local/python/lib/python3.6/asyncio/sslproto.py", line 505, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/local/python/lib/python3.6/asyncio/sslproto.py", line 201, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/local/python/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)
```

we have an script like this, and its working ok

```!python
def main():
    db_endpoint = queries.uri(**DB_INFO)
    import sqlalchemy as sa
    db_engine = sa.create_engine(db_endpoint)
    db.create_all(bind=db_engine)
    db_engine.dispose()
```

can you help me about

**Comment by fantix** [comment]
@ppsirg you are probably having the same issue as discussed in #428. The solution would be either to trust the possibly-self-signed certificate in your own `SSLContext`, or skip certificate verification at all in `SSLContext`.

> `    lambda: db.init_app(app, ssl=False, **DB_INFO)`

It is `ssl=True` in your traceback.

**Comment by ppsirg** [comment]
@fantix i think maybe the mistake was SSLContext i was working with (i mean, setting a boolean True on ssl option), despite [python docs says default Purpose is server auth](https://docs.python.org/3/library/ssl.html#ssl.create_default_context), i just defined it explicitly and worked nice (our certs were let's encypt certs)

```!#python
if DATABASE_SSL_ENABLED:
    context = SSLContext()
    context.load_default_certs(purpose=Purpose.SERVER_AUTH)
    DB_INFO['ssl'] = context

```

**Comment by fantix** [comment]
@ppsirg Cool, good to know it works for you, thanks for sharing!
