### ISSUE TITLE
Can't load plugin: sqlalchemy.dialects:postgresql.asyncpg

### ISSUE THREAD

**Issue by elad661** [fantix/gino#238]
* GINO version: 0.7.3
* Python version: Python 3.6.3
* asyncpg version: 0.15.0
* aiocontextvars version: 0.1.2
* PostgreSQL version: postgresql-9.2.23-3.el7_4.x86_64

I have an app using gino that works well on two Fedora machines running Python 3.6.5
However, on a CentOS 7 machine running Python 3.6.3, gino refuses to work:

```
Traceback (most recent call last):
  File "test.py", line 46, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "test.py", line 15, in main
    await db.set_bind('postgresql://localhost/gino')
  File "/home/test/.local/lib/python3.6/site-packages/gino/api.py", line 386, in set_bind
    bind = await create_engine(bind, loop=loop, **kwargs)
  File "/home/test/.local/lib/python3.6/site-packages/gino/strategies.py", line 22, in create
    dialect_cls = u.get_dialect()
  File "/home/test/.local/lib/python3.6/site-packages/sqlalchemy/engine/url.py", line 171, in get_dialect
    entrypoint = self._get_entrypoint()
  File "/home/test/.local/lib/python3.6/site-packages/sqlalchemy/engine/url.py", line 156, in _get_entrypoint
    cls = registry.load(name)
  File "/home/test/.local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 221, in load
    (self.group, name))
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgresql.asyncpg
```

To make sure it's not an issue with my code, I tried the code in the gino readme, and it too produced the same error.

Both the working setup and the non-working setup have `~/.local/lib/python3.6/site-packages/gino-0.7.3.dist-info/entry_points.txt` containing
```

    [sqlalchemy.dialects]
    postgresql.asyncpg = gino.dialects.asyncpg:AsyncpgDialect
    asyncpg = gino.dialects.asyncpg:AsyncpgDialect
```

(with the same newlines and indentation)

Any advice?

cc @salty-horse
see also: https://github.com/elad661/curlbus/issues/6

**Comment by elad661** [comment]
Okay, found the issue 2 minutes after reporting it: looks like gino doesn't work if you have setuptools 28.8.0 but does work if you have setuptools 39.2.0
(`pkg_resources`, which is used by SQLAlchemy for the entrypoints thing, doesn't seem to work with older setuptools)

**Comment by Pentusha** [comment]
Experiencing the same issue with gino 1.0.0 and setuptools 39.2.0 and azure functions.
```python
Result: Failure
Exception: NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgresql.asyncpg
Stack:   File "/azure-functions-host/workers/python/3.7/LINUX/X64/azure_functions_worker/dispatcher.py", line 311, in _handle__invocation_request
    call_result = await fi.func(**args)
  File "/home/site/wwwroot/queue_send_notification/__init__.py", line 19, in main
    await process_notification(deserialized)
  File "/home/site/wwwroot/shared/notifications/__init__.py", line 30, in process_notification
    await _send_email_notification(notification, emails)
  File "/home/site/wwwroot/shared/notifications/__init__.py", line 42, in _send_email_notification
    await get_db_engine()
  File "/home/site/wwwroot/shared/db.py", line 26, in get_db_engine
    bind = await create_engine(dsn)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/gino/strategies.py", line 33, in create
    dialect_cls = u.get_dialect()
  File "/home/site/wwwroot/.python_packages/lib/site-packages/sqlalchemy/engine/url.py", line 189, in get_dialect
    entrypoint = self._get_entrypoint()
  File "/home/site/wwwroot/.python_packages/lib/site-packages/sqlalchemy/engine/url.py", line 172, in _get_entrypoint
    cls = registry.load(name)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/sqlalchemy/util/langhelpers.py", line 268, in load
    "Can't load plugin: %s:%s" % (self.group, name)
```

```python
db = Gino()
engine = None

async def get_db_engine():
    global engine
    if not engine:
        dsn = get_dsn_from_config()
        bind = await create_engine(dsn)
        engine = await db.set_bind(bind)
        return engine
    return engine
```

**Comment by Ruzzz** [comment]
```python
from sqlalchemy.dialects import registry

registry.register('asyncpg', 'gino.dialects.asyncpg', 'AsyncpgDialect')
registry.register('postgresql.asyncpg', 'gino.dialects.asyncpg', 'AsyncpgDialect')
```
