### ISSUE TITLE
Conflicting SQLAlchemy Versions

### ISSUE THREAD

**Issue by EndenDragon** [fantix/gino#270]
Hello, I am having this issue:
```
Traceback (most recent call last):
  File "/home/ubuntu/workspace/discordbot/run.py", line 11, in <module>
    main()
  File "/home/ubuntu/workspace/discordbot/run.py", line 7, in main
    te.run()
  File "/home/ubuntu/workspace/discordbot/titanembeds/bot.py", line 48, in run
    self.loop.run_until_complete(self.start())
  File "/usr/lib/python3.5/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 240, in _step
    result = coro.send(None)
  File "/home/ubuntu/workspace/discordbot/titanembeds/bot.py", line 59, in start
    await self.database.connect(config["database-uri"])
  File "/home/ubuntu/workspace/discordbot/titanembeds/database/__init__.py", line 21, in connect
    await db.set_bind(dburi)
  File "/usr/local/lib/python3.5/dist-packages/gino/api.py", line 386, in set_bind
    bind = await create_engine(bind, loop=loop, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/gino/strategies.py", line 22, in create
    dialect_cls = u.get_dialect()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/url.py", line 171, in get_dialect
    entrypoint = self._get_entrypoint()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/url.py", line 156, in _get_entrypoint
    cls = registry.load(name)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/langhelpers.py", line 217, in load
    return impl.load()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2320, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2343, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 782, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (SQLAlchemy 1.2.9 (/usr/local/lib/python3.5/dist-packages), Requirement.parse('SQLAlchemy==1.2.8'))
Exception ignored in: <bound method ClientSession.__del__ of <aiohttp.client.ClientSession object at 0x7ff5a190a438>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client.py", line 216, in __del__
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1290, in call_exception_handler
  File "/usr/lib/python3.5/logging/__init__.py", line 1314, in error
  File "/usr/lib/python3.5/logging/__init__.py", line 1421, in _log
  File "/usr/lib/python3.5/logging/__init__.py", line 1431, in handle
  File "/usr/lib/python3.5/logging/__init__.py", line 1493, in callHandlers
  File "/usr/lib/python3.5/logging/__init__.py", line 861, in handle
  File "/usr/lib/python3.5/logging/__init__.py", line 1053, in emit
  File "/usr/lib/python3.5/logging/__init__.py", line 1043, in _open
NameError: name 'open' is not defined
Exception ignored in: <bound method ClientSession.__del__ of <aiohttp.client.ClientSession object at 0x7ff5a196a2e8>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client.py", line 216, in __del__
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1290, in call_exception_handler
  File "/usr/lib/python3.5/logging/__init__.py", line 1314, in error
  File "/usr/lib/python3.5/logging/__init__.py", line 1421, in _log
  File "/usr/lib/python3.5/logging/__init__.py", line 1431, in handle
  File "/usr/lib/python3.5/logging/__init__.py", line 1493, in callHandlers
  File "/usr/lib/python3.5/logging/__init__.py", line 861, in handle
  File "/usr/lib/python3.5/logging/__init__.py", line 1053, in emit
  File "/usr/lib/python3.5/logging/__init__.py", line 1043, in _open
NameError: name 'open' is not defined
```

I can prevent this issue by installing an older version of SQLAlchemy 1.2.8

My pip freeze:
```
jkzhang:~/workspace (gino) $ pip freeze
aiocontextvars==0.1.2
aiohttp==3.3.2
aioredis==1.1.0
alembic==0.9.5
amqp==2.3.2
asn1crypto==0.24.0
async-generator==1.9
async-timeout==3.0.0
asyncio-extras==1.3.2
asyncio-redis==0.14.3
asyncpg==0.16.0
attrs==18.1.0
Babel==2.6.0
beautifulsoup4==4.4.1
blinker==1.3
certifi==2018.4.16
cffi==1.11.5
chardet==3.0.4
click==6.7
colorama==0.2.5
croniter==0.3.24
cryptography==2.2.2
decorator==3.4.0
discord.py==1.0.0a1487+gface1d9
enum-compat==0.0.2
eventlet==0.21.0
extras==0.0.3
fixtures==2.0.0
Flask==1.0.2
Flask-Babel==0.11.2
Flask-Gravatar==0.4.2
Flask-HTMLmin==1.2
Flask-Limiter==1.0.1
Flask-Login==0.3.2
Flask-Mail==0.9.1
Flask-Migrate==2.0.3
Flask-Principal==0.4.0
Flask-Redis==0.3.0
Flask-RQ2==18.0
Flask-Script==2.0.5
Flask-Security==1.7.5
Flask-SocketIO==3.0.1
Flask-SQLAlchemy==2.3.2
Flask-SSLify==0.1.5
Flask-WTF==0.12
gevent==1.2.2
gevent-websocket==0.10.1
gino==0.7.4
greenlet==0.4.12
hiredis==0.2.0
html5lib==1.0b3
htmlmin==0.1.10
idna==2.7
idna-ssl==1.1.0
ipython==1.2.1
itsdangerous==0.24
Jinja2==2.10
kombu==4.2.1
limits==1.3
linecache2==1.0.0
Mako==1.0.7
MarkupSafe==1.0
matplotlib==1.3.1
multidict==4.3.1
nose==1.3.1
numpy==1.8.2
oauthlib==2.1.0
passlib==1.6.2
patreon==0.5.0
paypalrestsdk==1.13.1
pbr==1.9.1
pgadmin4==1.6
Pillow==2.3.0
psycopg2==2.7.3.1
pycparser==2.18
pycrypto==2.6.1
pycurl==7.19.3
pygobject==3.12.0
PyMySQL==0.7.11
PyNaCl==1.0.1
pyOpenSSL==18.0.0
pyparsing==2.0.1
pyrsistent==0.11.13
python-apt===0.9.3.5ubuntu2
python-dateutil==2.5.0
python-editor==1.0.3
python-engineio==2.2.0
python-mimeparse==1.5.1
python-socketio==2.0.0
pytz==2018.5
redis==2.10.6
Represent==1.5.1
requests==2.19.1
requests-oauthlib==1.0.0
rq==0.11.0
rq-scheduler==0.8.3
scipy==0.13.3
simplegeneric==0.8.1
simplejson==3.6.5
six==1.11.0
speaklater==1.3
sqlacrossover==0.2.2
SQLAlchemy==1.2.8
sqlalchemy-aio==0.11.0
sqlparse==0.1.19
testtools==2.3.0
tornado==3.1.1
traceback2==1.4.0
unattended-upgrades==0.1
unittest2==1.1.0
urllib3==1.23
uWSGI==2.0.15
vine==1.1.4
websockets==5.0.1
Werkzeug==0.14.1
WTForms==2.0.2
yarl==1.2.6
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

According to gino's requirements, I need SQLAlchemy 1.2.9, but that caused the crash above. Any ideas on what to do? Should I keep running on 1.2.8 SqlAlchemy?

**Comment by EndenDragon** [comment]
Sorry I figured out the issue. The gino on pypi needs 1.2.8 while the master branch has 1.2.9
I became confused for a moment.
