### ISSUE TITLE
Checking for the existence of a row

### ISSUE THREAD

**Issue by ape364** [fantix/gino#299]
* GINO version: 0.7.5
* Python version: 3.7.0
* asyncpg version: 0.17.0
* aiocontextvars version: 0.1.2
* PostgreSQL version: 10.4

### Description

Checking for the existence of a row

### What I Did

```
is_exists = await db.SomeModel.query.where(db.SomeModel.name == some_name).gino.first()
```

```
Traceback (most recent call last):
  File "/home/ape364/myproj/venv/lib/python3.7/site-packages/aiogram/dispatcher/__init__.py", line 256, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates)):
  File "/home/ape364/myproj/venv/lib/python3.7/site-packages/aiogram/dispatcher/__init__.py", line 119, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/ape364/myproj/venv/lib/python3.7/site-packages/aiogram/dispatcher/handler.py", line 74, in notify
    response = await handler(*args)
  File "/home/ape364/myproj/venv/lib/python3.7/site-packages/aiogram/dispatcher/__init__.py", line 137, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/ape364/myproj/venv/lib/python3.7/site-packages/aiogram/dispatcher/handler.py", line 74, in notify
    response = await handler(*args)
  File "/home/ape364/myproj/tgbot/handlers/test.py", line 32, in cmd_test
    is_exists = await db.SomeModel.query.where(db.SomeModel.name == some_name).gino.first()
  File "/home/ape364/myproj/venv/lib/python3.7/site-packages/gino/api.py", line 134, in first
    return await self._query.bind.first(self._query, *multiparams,
AttributeError: 'NoneType' object has no attribute 'first'
```

**Comment by wwwjfy** [comment]
Looks like it doesn't have the engine initialized properly. Could you share how you did that?

**Comment by ape364** [comment]
oh, sorry. forgot to call this:

```
async def init_db():
    await db.set_bind(settings.DB_DSN)
    await db.gino.create_all()
```

thanks, solved :+1:
