### ISSUE TITLE
Can not connect with sanic

### ISSUE THREAD

**Issue by rana-ahmed** [fantix/gino#344]
I'm trying to connect with sanic using this [doc](https://github.com/fantix/gino/blob/master/docs/sanic.rst). But I can't start the sanic server
`web_1  | [2018-09-20 16:10:09 +0600] [1] [INFO] Goin' Fast @ http://0.0.0.0:5000
web_1  | Executing <Task pending coro=<before_server_start() running at /usr/local/lib/python3.6/site-packages/gino/ext/sanic.py:124> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f878f697b88>()] created at /usr/local/lib/python3.6/asyncio/tasks.py:341> cb=[run_until_complete.<locals>.<lambda>()] created at /usr/local/lib/python3.6/site-packages/sanic/server.py:496> took 0.194 seconds
web_1  | [2018-09-20 16:10:09 +0600] [1] [ERROR] Experienced exception while trying to serve
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 646, in run
web_1  |     serve(**server_settings)
web_1  |   File "/usr/local/lib/python3.6/site-packages/sanic/server.py", line 588, in serve
web_1  |     trigger_events(before_start, loop)
web_1  |   File "/usr/local/lib/python3.6/site-packages/sanic/server.py", line 496, in trigger_events
web_1  |     loop.run_until_complete(result)
web_1  |   File "uvloop/loop.pyx", line 1448, in uvloop.loop.Loop.run_until_complete
web_1  |   File "/usr/local/lib/python3.6/site-packages/gino/ext/sanic.py", line 124, in before_server_start
web_1  |     loop=loop,
web_1  |   File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
web_1  |     return self.gen.send(None)
web_1  |   File "/usr/local/lib/python3.6/site-packages/gino/ext/sanic.py", line 142, in set_bind
web_1  |     return await super().set_bind(bind, loop=loop, **kwargs)
web_1  |   File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
web_1  |     return self.gen.send(None)
web_1  |   File "/usr/local/lib/python3.6/site-packages/gino/api.py", line 386, in set_bind
web_1  |     bind = await create_engine(bind, loop=loop, **kwargs)
web_1  |   File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
web_1  |     return self.gen.send(None)
web_1  |   File "/usr/local/lib/python3.6/site-packages/gino/strategies.py", line 42, in create
web_1  |     pool = await dialect.init_pool(u, loop)
web_1  |   File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
web_1  |     return self.gen.send(None)
web_1  |   File "/usr/local/lib/python3.6/site-packages/gino/dialects/asyncpg.py", line 318, in init_pool
web_1  |     **self._pool_kwargs)
web_1  |   File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
web_1  |     return self.gen.send(None)
web_1  |   File "/usr/local/lib/python3.6/site-packages/gino/dialects/asyncpg.py", line 209, in _init
web_1  |     self._pool = await asyncpg.create_pool(**args)
web_1  |   File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
web_1  |     return self.gen.send(None)
web_1  |   File "/usr/local/lib/python3.6/site-packages/asyncpg/pool.py", line 398, in _async__init__
web_1  |     await self._initialize()
web_1  |   File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
web_1  |     return self.gen.send(None)
web_1  |   File "/usr/local/lib/python3.6/site-packages/asyncpg/pool.py", line 415, in _initialize
web_1  |     await first_ch.connect()
web_1  |   File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
web_1  |     return self.gen.send(None)
web_1  |   File "/usr/local/lib/python3.6/site-packages/asyncpg/pool.py", line 125, in connect
web_1  |     self._con = await self._pool._get_new_connection()
web_1  |   File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
web_1  |     return self.gen.send(None)
web_1  |   File "/usr/local/lib/python3.6/site-packages/asyncpg/pool.py", line 461, in _get_new_connection
web_1  |     **self._connect_kwargs)
web_1  |   File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
web_1  |     return self.gen.send(None)
web_1  |   File "/usr/local/lib/python3.6/site-packages/asyncpg/connection.py", line 1602, in connect
web_1  |     max_cacheable_statement_size=max_cacheable_statement_size)
web_1  |   File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
web_1  |     return self.gen.send(None)
web_1  |   File "/usr/local/lib/python3.6/site-packages/asyncpg/connect_utils.py", line 434, in _connect
web_1  |     raise last_error
web_1  |   File "/usr/local/lib/python3.6/site-packages/asyncpg/connect_utils.py", line 426, in _connect
web_1  |     connection_class=connection_class)
web_1  |   File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
web_1  |     return self.gen.send(None)
web_1  |   File "/usr/local/lib/python3.6/site-packages/asyncpg/connect_utils.py", line 396, in _connect_addr
web_1  |     connector, timeout=timeout, loop=loop)
web_1  |   File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
web_1  |     return fut.result()
web_1  |   File "uvloop/loop.pyx", line 1884, in create_connection
web_1  | OSError: Multiple exceptions: [Errno 111] Connection refused, [Errno 99] Cannot assign requested address
web_1  | Traceback (most recent call last):
web_1  |   File "app.py", line 66, in <module>
web_1  |     app.run(host="0.0.0.0", port=5000, debug=True)
web_1  |   File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 646, in run
web_1  |     serve(**server_settings)
web_1  |   File "/usr/local/lib/python3.6/site-packages/sanic/server.py", line 588, in serve
web_1  |     trigger_events(before_start, loop)
web_1  |   File "/usr/local/lib/python3.6/site-packages/sanic/server.py", line 496, in trigger_events
web_1  |     loop.run_until_complete(result)
web_1  |   File "uvloop/loop.pyx", line 1448, in uvloop.loop.Loop.run_until_complete
web_1  |   File "/usr/local/lib/python3.6/site-packages/gino/ext/sanic.py", line 124, in before_server_start
web_1  |     loop=loop,
web_1  |   File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
web_1  |     return self.gen.send(None)
web_1  |   File "/usr/local/lib/python3.6/site-packages/gino/ext/sanic.py", line 142, in set_bind
web_1  |     return await super().set_bind(bind, loop=loop, **kwargs)
web_1  |   File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
web_1  |     return self.gen.send(None)
web_1  |   File "/usr/local/lib/python3.6/site-packages/gino/api.py", line 386, in set_bind
web_1  |     bind = await create_engine(bind, loop=loop, **kwargs)
web_1  |   File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
web_1  |     return self.gen.send(None)
web_1  |   File "/usr/local/lib/python3.6/site-packages/gino/strategies.py", line 42, in create
web_1  |     pool = await dialect.init_pool(u, loop)
web_1  |   File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
web_1  |     return self.gen.send(None)
web_1  |   File "/usr/local/lib/python3.6/site-packages/gino/dialects/asyncpg.py", line 318, in init_pool
web_1  |     **self._pool_kwargs)
web_1  |   File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
web_1  |     return self.gen.send(None)
web_1  |   File "/usr/local/lib/python3.6/site-packages/gino/dialects/asyncpg.py", line 209, in _init
web_1  |     self._pool = await asyncpg.create_pool(**args)
web_1  |   File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
web_1  |     return self.gen.send(None)
web_1  |   File "/usr/local/lib/python3.6/site-packages/asyncpg/pool.py", line 398, in _async__init__
web_1  |     await self._initialize()
web_1  |   File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
web_1  |     return self.gen.send(None)
web_1  |   File "/usr/local/lib/python3.6/site-packages/asyncpg/pool.py", line 415, in _initialize
web_1  |     await first_ch.connect()
web_1  |   File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
web_1  |     return self.gen.send(None)
web_1  |   File "/usr/local/lib/python3.6/site-packages/asyncpg/pool.py", line 125, in connect
web_1  |     self._con = await self._pool._get_new_connection()
web_1  |   File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
web_1  |     return self.gen.send(None)
web_1  |   File "/usr/local/lib/python3.6/site-packages/asyncpg/pool.py", line 461, in _get_new_connection
web_1  |     **self._connect_kwargs)
web_1  |   File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
web_1  |     return self.gen.send(None)
web_1  |   File "/usr/local/lib/python3.6/site-packages/asyncpg/connection.py", line 1602, in connect
web_1  |     max_cacheable_statement_size=max_cacheable_statement_size)
web_1  |   File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
web_1  |     return self.gen.send(None)
web_1  |   File "/usr/local/lib/python3.6/site-packages/asyncpg/connect_utils.py", line 434, in _connect
web_1  |     raise last_error
web_1  |   File "/usr/local/lib/python3.6/site-packages/asyncpg/connect_utils.py", line 426, in _connect
web_1  |     connection_class=connection_class)
web_1  |   File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
web_1  |     return self.gen.send(None)
web_1  |   File "/usr/local/lib/python3.6/site-packages/asyncpg/connect_utils.py", line 396, in _connect_addr
web_1  |     connector, timeout=timeout, loop=loop)
web_1  |   File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
web_1  |     return fut.result()
web_1  |   File "uvloop/loop.pyx", line 1884, in create_connection
web_1  | OSError: Multiple exceptions: [Errno 111] Connection refused, [Errno 99] Cannot assign requested address
web_1  | sys:1: RuntimeWarning: coroutine 'Loop.create_server' was never awaited`

**Comment by wwwjfy** [comment]
I edited to fix the format.

From the error `Cannot assign requested address`, I suspect there is another instance using port 5000. Could you check?

If this couldn't fix it, is it possible to paste your code here? So I can try to reproduce.

**Comment by rana-ahmed** [comment]
Thanks @wwwjfy :) 5000 port not in use, I checked. Here is my code
`
from sanic import Sanic
from sanic.response import json
from gino.ext.sanic import Gino

app = Sanic()
db = Gino()
db.init_app(app)


class Issue(db.Model):
    __tablename__ = 'issues'

    id = db.Column(db.Integer(), primary_key=True)
    order_id = db.Column(db.String(256), unique=True)


@app.route("/")
async def get_issue(request):
    issue = await Issue.get_or_404(int(1))
    return json({'order': issue.order_id})


if __name__ == '__main__':
    app.run(host="0.0.0.0", port=5000, debug=True)
`

**Comment by wwwjfy** [comment]
I'm not sure why `Cannot assign requested address` is here, but from the traceback, it can't connect to postgresql. The connection defaults to localhost:5432. Looks like you're using Docker? can you check if postgresql is running in the same container (or same machine if it's not docker) and the port is 5432?

**Comment by rana-ahmed** [comment]
Thank you @wwwjfy it was db connection issue. I fixed it by setting all necessary value
```
app = Sanic()
app.config.DB_HOST = 'db'
app.config.DB_PORT = '5432'
app.config.DB_USER = 'postgres'
app.config.DB_DATABASE = 'postgres'
db = Gino()
db.init_app(app)
```
