### ISSUE TITLE
module 'importlib._bootstrap' has no attribute 'SourceFileLoader'

### ISSUE THREAD

**Issue by freenetwork** [fantix/gino#414]
* GINO version: 0.8.1
* Python version: 3.7
* asyncpg version: 0.18.2
* aiocontextvars version:
* PostgreSQL version: 9.5

### Description

```
Traceback (most recent call last):
  File "async.py", line 110, in lists_details
    engine = await db.set_bind('postgresql://soc:123QAZxsw@localhost:5432/soc', min_size=0, max_size=50)
  File "/home/mrdss/orion/wss/lib/python3.7/site-packages/gino/api.py", line 390, in set_bind
    bind = await create_engine(bind, loop=loop, **kwargs)
  File "/home/mrdss/orion/wss/lib/python3.7/site-packages/gino/strategies.py", line 22, in create
    dialect_cls = u.get_dialect()
  File "/home/mrdss/orion/wss/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 171, in get_dialect
    entrypoint = self._get_entrypoint()
  File "/home/mrdss/orion/wss/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 156, in _get_entrypoint
    cls = registry.load(name)
  File "/home/mrdss/orion/wss/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 210, in load
    import pkg_resources
  File "/home/mrdss/orion/wss/lib/python3.7/site-packages/pkg_resources.py", line 1479, in <module>
    register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
```

**Comment by wwwjfy** [comment]
This looks not related to Gino. Could you try to update setuptools? `pip install -U setuptools`?
