### ISSUE TITLE
Using gino in Sanic when db server isn't up shouldn't crash

### ISSUE THREAD

**Issue by igozali** [fantix/gino#523]
* GINO version: 0.8.3
* Python version: 3.7.4
* asyncpg version: 0.18.3
* aiocontextvars version: 0.2.2
* PostgreSQL version: 11.5

### Description

**Expected:**
If I have a Sanic server with Gino initialized lazily (example below), I expect to at least still be able to start up my server without issues. Even if later API calls that access the database would fail, I can still return a 503 back to the user. Phrased another way, outages in external services (`postgresql` in this case) should not affect my ability to start up my server.

For reference, `Flask-SQLAlchemy` has this behavior where I can still start up my Flask server even if I don't have any databases running.

Would it be possible to initialize the connection lazily (e.g. when calling `db.query.all()`) and not during the `db.init_app(app)` call? 

Possibly related: https://github.com/fantix/gino/issues/426

**Actual:**
Sanic server crashes during start up.

### What I Did

Minimal, reproducible example follows.

Example `main.py.`
```py
from sanic import Sanic
from gino.ext.sanic import Gino

app = Sanic()
app.config["DB_DSN"] = "postgresql://postgres@localhost/postgres"

db = Gino()
db.init_app(app)

app.run()
```

If I run without postgresql turned on, server start up crashes with the following traceback:
```
$ python3 main.py$ python3 main.py
[2019-08-15 11:34:03 -0700] [7278] [INFO] Goin' Fast @ http://127.0.0.1:8000
[2019-08-15 11:34:03 -0700] [7278] [ERROR] Experienced exception while trying to serve
Traceback (most recent call last):
  File "/Users/**redacted**/.local/share/virtualenvs/api-IivKMfqw/lib/python3.7/site-packages/sanic/app.py", line 1133, in run
    serve(**server_settings)
  File "/Users/**redacted**/.local/share/virtualenvs/api-IivKMfqw/lib/python3.7/site-packages/sanic/server.py", line 775, in serve
    trigger_events(before_start, loop)
  File "/Users/**redacted**/.local/share/virtualenvs/api-IivKMfqw/lib/python3.7/site-packages/sanic/server.py", line 633, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1417, in uvloop.loop.Loop.run_until_complete
  File "/Users/**redacted**/.local/share/virtualenvs/api-IivKMfqw/lib/python3.7/site-packages/gino/ext/sanic.py", line 116, in before_server_start
    **app.config.setdefault('DB_KWARGS', dict()),
  File "/Users/**redacted**/.local/share/virtualenvs/api-IivKMfqw/lib/python3.7/site-packages/gino/ext/sanic.py", line 131, in set_bind
    return await super().set_bind(bind, loop=loop, **kwargs)
  File "/Users/**redacted**/.local/share/virtualenvs/api-IivKMfqw/lib/python3.7/site-packages/gino/api.py", line 390, in set_bind
    bind = await create_engine(bind, loop=loop, **kwargs)
  File "/Users/**redacted**/.local/share/virtualenvs/api-IivKMfqw/lib/python3.7/site-packages/gino/strategies.py", line 43, in create
    pool = await dialect.init_pool(u, loop, pool_class=pool_class)
  File "/Users/**redacted**/.local/share/virtualenvs/api-IivKMfqw/lib/python3.7/site-packages/gino/dialects/asyncpg.py", line 368, in init_pool
    **self._pool_kwargs)
  File "/Users/**redacted**/.local/share/virtualenvs/api-IivKMfqw/lib/python3.7/site-packages/gino/dialects/asyncpg.py", line 213, in _init
    self._pool = await asyncpg.create_pool(**args)
  File "/Users/**redacted**/.local/share/virtualenvs/api-IivKMfqw/lib/python3.7/site-packages/asyncpg/pool.py", line 400, in _async__init__
    await self._initialize()
  File "/Users/**redacted**/.local/share/virtualenvs/api-IivKMfqw/lib/python3.7/site-packages/asyncpg/pool.py", line 417, in _initialize
    await first_ch.connect()
  File "/Users/**redacted**/.local/share/virtualenvs/api-IivKMfqw/lib/python3.7/site-packages/asyncpg/pool.py", line 125, in connect
    self._con = await self._pool._get_new_connection()
  File "/Users/**redacted**/.local/share/virtualenvs/api-IivKMfqw/lib/python3.7/site-packages/asyncpg/pool.py", line 463, in _get_new_connection
    **self._connect_kwargs)
  File "/Users/**redacted**/.local/share/virtualenvs/api-IivKMfqw/lib/python3.7/site-packages/asyncpg/connection.py", line 1688, in connect
    max_cacheable_statement_size=max_cacheable_statement_size)
  File "/Users/**redacted**/.local/share/virtualenvs/api-IivKMfqw/lib/python3.7/site-packages/asyncpg/connect_utils.py", line 551, in _connect
    raise last_error
  File "/Users/**redacted**/.local/share/virtualenvs/api-IivKMfqw/lib/python3.7/site-packages/asyncpg/connect_utils.py", line 543, in _connect
    connection_class=connection_class)
  File "/Users/**redacted**/.local/share/virtualenvs/api-IivKMfqw/lib/python3.7/site-packages/asyncpg/connect_utils.py", line 513, in _connect_addr
    connector, timeout=timeout, loop=loop)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "uvloop/loop.pyx", line 1927, in create_connection
  File "uvloop/loop.pyx", line 1906, in uvloop.loop.Loop.create_connection
ConnectionRefusedError: [Errno 61] Connection refused
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    app.run()
  File "/Users/**redacted**/.local/share/virtualenvs/api-IivKMfqw/lib/python3.7/site-packages/sanic/app.py", line 1133, in run
    serve(**server_settings)
  File "/Users/**redacted**/.local/share/virtualenvs/api-IivKMfqw/lib/python3.7/site-packages/sanic/server.py", line 775, in serve
    trigger_events(before_start, loop)
  File "/Users/**redacted**/.local/share/virtualenvs/api-IivKMfqw/lib/python3.7/site-packages/sanic/server.py", line 633, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1417, in uvloop.loop.Loop.run_until_complete
  File "/Users/**redacted**/.local/share/virtualenvs/api-IivKMfqw/lib/python3.7/site-packages/gino/ext/sanic.py", line 116, in before_server_start
    **app.config.setdefault('DB_KWARGS', dict()),
  File "/Users/**redacted**/.local/share/virtualenvs/api-IivKMfqw/lib/python3.7/site-packages/gino/ext/sanic.py", line 131, in set_bind
    return await super().set_bind(bind, loop=loop, **kwargs)
  File "/Users/**redacted**/.local/share/virtualenvs/api-IivKMfqw/lib/python3.7/site-packages/gino/api.py", line 390, in set_bind
    bind = await create_engine(bind, loop=loop, **kwargs)
  File "/Users/**redacted**/.local/share/virtualenvs/api-IivKMfqw/lib/python3.7/site-packages/gino/strategies.py", line 43, in create
    pool = await dialect.init_pool(u, loop, pool_class=pool_class)
  File "/Users/**redacted**/.local/share/virtualenvs/api-IivKMfqw/lib/python3.7/site-packages/gino/dialects/asyncpg.py", line 368, in init_pool
    **self._pool_kwargs)
  File "/Users/**redacted**/.local/share/virtualenvs/api-IivKMfqw/lib/python3.7/site-packages/gino/dialects/asyncpg.py", line 213, in _init
    self._pool = await asyncpg.create_pool(**args)
  File "/Users/**redacted**/.local/share/virtualenvs/api-IivKMfqw/lib/python3.7/site-packages/asyncpg/pool.py", line 400, in _async__init__
    await self._initialize()
  File "/Users/**redacted**/.local/share/virtualenvs/api-IivKMfqw/lib/python3.7/site-packages/asyncpg/pool.py", line 417, in _initialize
    await first_ch.connect()
  File "/Users/**redacted**/.local/share/virtualenvs/api-IivKMfqw/lib/python3.7/site-packages/asyncpg/pool.py", line 125, in connect
    self._con = await self._pool._get_new_connection()
  File "/Users/**redacted**/.local/share/virtualenvs/api-IivKMfqw/lib/python3.7/site-packages/asyncpg/pool.py", line 463, in _get_new_connection
    **self._connect_kwargs)
  File "/Users/**redacted**/.local/share/virtualenvs/api-IivKMfqw/lib/python3.7/site-packages/asyncpg/connection.py", line 1688, in connect
    max_cacheable_statement_size=max_cacheable_statement_size)
  File "/Users/**redacted**/.local/share/virtualenvs/api-IivKMfqw/lib/python3.7/site-packages/asyncpg/connect_utils.py", line 551, in _connect
    raise last_error
  File "/Users/**redacted**/.local/share/virtualenvs/api-IivKMfqw/lib/python3.7/site-packages/asyncpg/connect_utils.py", line 543, in _connect
    connection_class=connection_class)
  File "/Users/**redacted**/.local/share/virtualenvs/api-IivKMfqw/lib/python3.7/site-packages/asyncpg/connect_utils.py", line 513, in _connect_addr
    connector, timeout=timeout, loop=loop)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "uvloop/loop.pyx", line 1927, in create_connection
  File "uvloop/loop.pyx", line 1906, in uvloop.loop.Loop.create_connection
ConnectionRefusedError: [Errno 61] Connection refused
sys:1: RuntimeWarning: coroutine 'Loop.create_server' was never awaited
```

**Comment by mikekeda** [comment]
As for me, it's normal behavior, for example Django will crash if connect to db fails.

If you want to implement custom database bind initializing, you shouldn't use db.init_app(app).
Add all needed functionality to before_server_start, after_server_stop listeners and request, response middlewares.

example:
```
        @app.listener('before_server_start')
        async def before_server_start(_, loop):
            for t in (0, 1, 3, 10):
                try:
                    if t:
                        sleep(t)

                    # set bind

                    break  # bind was set, break the loop
                except ConnectionRefusedError:
                    pass
```

**Comment by igozali** [comment]
Ah, interesting, thanks for the approach. But if the database is still down after 15 seconds, this would still fail my server startup, right?

I was wondering if it would make sense to initialize `Gino` without having to call `set_bind` in the 'before_server_start' listener (especially since `set_bind` calls `create_engine` internally), and only initialize the binds at the point it's needed (e.g. like when I call `db.query.all()` or `db.query.first()`). The downside to this approach seems to be creating the engine over and over again, which we may mitigate by lazily saving the engine.

**Comment by wwwjfy** [comment]
While I do understand where it's from, I'd argue that if anything is going to fail, we want it to fail early and fast, so we could act early and fast.
I suppose it's safe to assume database is the hard dependency for the server (otherwise, I'd have a separate server to serve all those non db required requests). Failure to connect to db could be considered as failure to start.
The other benefit of pool initialization at boot time is the first request won't suffer from high latency.
If we want to return errors to client side instead of connection refused, I would add a load balancer in front of the servers.

It is indeed possible to add the "feature", but may not be worth it.

**Comment by igozali** [comment]
Alright, then I'll close this issue. Thanks for the discussion.
