### ISSUE TITLE
Error when create record in Sanic

### ISSUE THREAD

**Issue by jonahfang** [fantix/gino#56]
* GINO version: 0.5.0
* Python version: 3.6.2
* Operating System: Ubuntu 14.04

### Description

Error to create record in Sanic after upgraded to version 0.5.0

### What I Did

```
@bp.post('/users')
async def add_new_user(request):
    new_obj = request.json   #dict
    u = await User.create(**new_obj)
    return ajax_maint_ok(u.id)
```
Call it like this:
```
DATA='{"nickname":"n1"}'

curl \
 http://dserver:9901/demo/users \
 -X POST \
 -H "Content-Type: application/json" \
 -H "Accept: text/html,application/json" \
 -d ${DATA}
```

**Comment by jonahfang** [comment]
Error msg:
```
[2017-09-05 Tue 17:05:26.278][fusion2_api_min.local]Exception occurred while handling uri: "http://dserver:9901/demo/users"
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 503, in handle_request
    response = await response
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 109, in __next__
    return self.gen.send(None)
  File "/src/apps/demo/views/user_crud.py", line 20, in add_new_user
    u = await User.create(**new_obj)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 109, in __next__
    return self.gen.send(None)
  File "/usr/local/lib/python3.6/site-packages/gino/crud.py", line 162, in create
    row = await cls.__metadata__.first(q, bind=bind)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 109, in __next__
    return self.gen.send(None)
  File "/usr/local/lib/python3.6/site-packages/gino/api.py", line 178, in first
    bind or self.bind, clause, *multiparams, **params)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 109, in __next__
    return self.gen.send(None)
  File "/usr/local/lib/python3.6/site-packages/gino/dialect.py", line 202, in do_first
    row = await bind.fetchrow(context.statement, *context.parameters[0],
AttributeError: 'NoneType' object has no attribute 'fetchrow'

```

**Comment by fantix** [comment]
Please also paste the part where `gino.ext.sanic.Gino.init_app` occurs.

**Comment by jonahfang** [comment]
server.py
```
import os
from importlib import import_module
from sanic import Sanic,response
from sanic_redis import SanicRedis
from gino.ext.sanic import Gino as SanicGino
from gino import Gino
from apps.utils.common import get_env
from apps.utils.log import log_event
from apps.utils.http_client import Client
from .settings import REDIS_CONFIG,DB_CONFIG,DEBUG,LOGGING,INSTALLED_APPS

log_config = LOGGING if DEBUG else None
app = Sanic(log_config=log_config)

for installed_app in INSTALLED_APPS:
    m = import_module(f'{installed_app}.views')
    app.blueprint(m.bp)

if REDIS_CONFIG:
    app.config.update({'REDIS': REDIS_CONFIG})
    redis = SanicRedis(app)

if DB_CONFIG:
    app.config.DB_HOST = DB_CONFIG['host']
    app.config.DB_USER = DB_CONFIG['user']
    app.config.DB_PORT = DB_CONFIG['port']
    app.config.DB_PASSWORD = DB_CONFIG['password']
    app.config.DB_DATABASE = DB_CONFIG['database']
    SanicGino().init_app(app)

@app.listener('before_server_start')
async def before_server_start(app,loop):
    if DB_CONFIG:
        db = SanicGino()
        app.pool = await db.create_pool('postgresql://{user}:{password}@{host}:{port}/{database}'.format(**DB_CONFIG))
        app.db = db
    app.client = Client()

@app.listener('before_server_stop')
async def before_server_stop(app,loop):
    app.client.close()

@app.route("/")
async def test(request):
    return response.json({"hello": "world"})

if __name__ == "__main__":
    SANIC_PREFIX = 'SANIC_'
    for k, v in os.environ.items():
        if k.startswith(SANIC_PREFIX):
            _, config_key = k.split(SANIC_PREFIX, 1)
            app.config[config_key] = v

    port = 80
    if DEBUG:
        port = 8000
    app.run(host="0.0.0.0", port=port, debug=DEBUG, workers=int(get_env('SANIC_WORKERS',1)))
```

**Comment by fantix** [comment]
```python
    SanicGino().init_app(app)
```
This would be the problem - this `db` object is gone after this line.

**Comment by jonahfang** [comment]
But it is ok in version 0.4.0

**Comment by jonahfang** [comment]
It still not work after changed to:
```
...
if DB_CONFIG:
    app.config.DB_HOST = DB_CONFIG['host']
    app.config.DB_USER = DB_CONFIG['user']
    app.config.DB_PORT = DB_CONFIG['port']
    app.config.DB_PASSWORD = DB_CONFIG['password']
    app.config.DB_DATABASE = DB_CONFIG['database']
    db = SanicGino()
    db.init_app(app)

@app.listener('before_server_start')
async def before_server_start(app,loop):
    if DB_CONFIG:
        app.pool = await db.create_pool('postgresql://{user}:{password}@{host}:{port}/{database}'.format(**DB_CONFIG))
        app.db = db
    app.client = Client()

```

**Comment by jonahfang** [comment]
It seems that `app.pool` is not needed.I have removed it.

**Comment by fantix** [comment]
I'd still suggest you follow the Flask-style extension usage:

1. Create extension as global variable:

```python
db = Gino()
```

2. Import and make use of extension:

```python
from ... import db

class User(db.Model):
    ...
```

3. Initialize extension during app creation:

```python
from ... import db

def get_app():
    app = Sanic()
    db.init_app(app)
```

**Comment by jonahfang** [comment]
Thanks, it works!

**Comment by fantix** [comment]
np, good to know
