### ISSUE TITLE
How to set up quart and Gino

### ISSUE THREAD

**Issue by horlahlekhon** [fantix/gino#566]
* GINO version: 0.8.3
* Python version: 3.7
* asyncpg version: 0.19.0
* aiocontextvars version: 0.2.2
* PostgreSQL version: 11

### Description

I want to use gino as an orm with quart, but i cant get it to connect together....
most of the time i get : Gino engine is not initialized. when i try to acess the db api when the server is running.

The database tables were created but when i try to insert , i get this. and nothing seem to work.

### What I Did
below is how i try to connect it
```python
from config import DevelopmentConfig
from quart import Quart
import asyncio
from gino import Gino

app = Quart(__name__)

app.config.from_object(DevelopmentConfig)
db = Gino()
from app.views import deep, neutral

app.register_blueprint(deep)
app.register_blueprint(neutral)

async def main():
    await db.set_bind(DevelopmentConfig.DATABASE_URI)
    await db.gino.create_all()

if __name__ == '__main__':
    app.run()
asyncio.get_event_loop().run_until_complete(main())


```

This is the error
```
Running on http://127.0.0.1:5000 (CTRL + C to quit)
[2019-10-11 16:52:12,978] Running on 127.0.0.1:5000 over http (CTRL + C to quit)
[2019-10-11 16:52:20,575] ERROR in app: Exception on request GET /telegram/messages/fetch
Traceback (most recent call last):
  File "/home/lekan/Documents/workspace/telegram-flask/lib/python3.7/site-packages/quart/app.py", line 1524, in handle_request
    return await self.full_dispatch_request(request_context)
  File "/home/lekan/Documents/workspace/telegram-flask/lib/python3.7/site-packages/quart/app.py", line 1546, in full_dispatch_request
    result = await self.handle_user_exception(error)
  File "/home/lekan/Documents/workspace/telegram-flask/lib/python3.7/site-packages/quart/app.py", line 957, in handle_user_exception
    raise error
  File "/home/lekan/Documents/workspace/telegram-flask/lib/python3.7/site-packages/quart/app.py", line 1544, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/home/lekan/Documents/workspace/telegram-flask/lib/python3.7/site-packages/quart/app.py", line 1592, in dispatch_request
    return await handler(**request_.view_args)
  File "/home/lekan/Documents/workspace/telegram-flask/deepview-telegram/app/views.py", line 72, in fetch
    msgs = await client.messages(limit=500)
  File "/home/lekan/Documents/workspace/telegram-flask/deepview-telegram/app/request.py", line 50, in messages
    msg = await DbMessage.get_messages(message_id=message.id)
  File "/home/lekan/Documents/workspace/telegram-flask/lib/python3.7/site-packages/gino/api.py", line 135, in first
    return await self._query.bind.first(self._query, *multiparams,
  File "/home/lekan/Documents/workspace/telegram-flask/lib/python3.7/site-packages/gino/api.py", line 501, in __getattribute__
    raise self._exception
gino.exceptions.UninitializedError: Gino engine is not initialized.
```

I also tried to do this  in my views: 

```python
@app.before_serving
async def main():
    await db.set_bind(DevelopmentConfig.DATABASE_URI)
    await db.gino.create_all()

asyncio.get_event_loop().run_until_complete(main())

```

but i get the same error.

Please i'd appreciate if you could help on how to connect and do db operations successfuly.

Thanks.

**Comment by wwwjfy** [comment]
I think the problem is the order of the executions.
For the first snippet, `app.run()` is "blocking", and `main()` never gets to run, therefore `db.set_bind` is not executed.

You may consider to use quart extension: `from gino.ext.quart import Gino`. The source code is here https://github.com/fantix/gino/blob/master/gino/ext/quart.py

**Comment by horlahlekhon** [comment]
using the `gino.ext.quart.Gino` Am not sure if i did it right but i initialized the db like : `db = Gino(app=app)`, but when i run, i still get the same error.

**Comment by wwwjfy** [comment]
could you also share the code so I can try to identify the cause?

**Comment by horlahlekhon** [comment]
__init__.py

```python

from config import DevelopmentConfig
from quart import Quart
from gino.ext.quart import Gino

app = Quart(__name__)

app.config.from_object(DevelopmentConfig)
db = Gino(app=app)
from app.views import deep, neutral

app.register_blueprint(deep)
app.register_blueprint(neutral)

if __name__ == '__main__':
    app.run()

```

request.py 
```
from telethon import TelegramClient
from telethon.errors import SessionPasswordNeededError
from .models import DbUser, DbMessage
from gino.exceptions import NoSuchRowError
from telethon.tl.types import Channel, Chat


class Connection(TelegramClient):
    def __init__(self, api_hash, api_id, phone):
        super(Connection, self).__init__(session=phone, api_hash=api_hash, api_id=api_id)
        self.phone = phone
        self.me = None

    async def get_code(self):
        return await self.send_code_request(self.phone)

    async def login(self, code=None, password=None):
        await self.connect()
        if not self.is_user_authorized():
            try:
                await self.sign_in(phone=self.phone, code=code)
            except SessionPasswordNeededError:
                await self.sign_in(phone=self.phone, code=code, password=password)
        me = await self.get_me()
        try:
            me = DbUser.get_users(me.id)
        except NoSuchRowError:
            me = DbUser.save_user(user_id=me.id, first_name=me.first_name)
        self.me = me
        return self


    async def messages(self, limit=100):
        dialogs = await self.get_dialogs(limit=limit)
        messages = None
        for dialog in dialogs:
            user = dialog.entity
            if (not isinstance(user, (Channel, Chat))) and user.first_name.find("bot") < 0 and (not user.is_self):
                try:
                    new_user = await DbUser.get_users(user.id)
                except NoSuchRowError:
                    new_user = await DbUser.save_user(user.id, user.first_name)

                messages = await self.get_messages(user, limit=limit)
                for message in messages:
                    try:
                        msg = await DbMessage.get_messages(message_id=message.id)
                        # msg.update_message()
                    except NoSuchRowError:
                        from_user = await DbUser.get_users(user_id=message.from_id)
                        to_user = await DbUser.get_users(user_id=message.to_id.user_id)
                        msg = await DbMessage.save_message(message_id=message.id, from_user=from_user, to_user=to_user, ts_created=message.date, message=message.message)
        return messages

```

models.py

```
from app import DevelopmentConfig
from gino.exceptions import NoSuchRowError
from gino import Gino

db = Gino()
class DbUser(db.Model):
    __tablename__ = 'users'

    user_id = db.Column(db.Integer, primary_key=True, unique=True)
    first_name  = db.Column(db.String(255))

    @classmethod
    async def save_user(cls, user_id, first_name):
        try:
            user = await DbUser.query.where(DbUser.user_id==user_id).gino.first()
        except NoSuchRowError:
            user = await DbUser.create(user_id=user_id, first_name=first_name)
            # user.save()
        return user

    @classmethod
    async def get_users(cls, user_id=None):
        if user_id:
            try:
                user = DbUser.query.where(DbUser.user_id==user_id).gino.first()
                return user
            except NoSuchRowError:
                return None
        return DbUser.query.all()


class DbMessage(db.Model):
    __tablename__= 'messages'

    message_id = db.Column(db.Integer,  primary_key=True, unique=True)
    from_user = db.Column(db.String(255))
    ts_created = db.Column(db.DateTime, nullable=False)
    chat = db.Column(db.Integer, db.ForeignKey('users.user_id', ondelete='CASCADE'), nullable=False)
    message = db.Column(db.Text)
    to_user = db.Column(db.Integer, db.ForeignKey('users.user_id', ondelete='CASCADE'))

    def __init__(self, message_id, from_user, ts_created, message, to_user):
        self.message_id = message_id
        self.from_user = from_user
        self.message = message
        self.ts_created = ts_created
        self.to_user = to_user

    def save(self):
        """
            save the new Message model into the database and commit the change
        """
        db.session.add(self)
        db.session.commit()
        return self.id

    @classmethod
    def save_message(cls, message_id, from_user, ts_created, message, to_user):
        try:
            message = DbMessage.query.where(DbMessage.message_id==message_id).gino.first()
            message.message = message
            # message.save()
        except NoSuchRowError:
            message = DbMessage.create(message_id, from_user, ts_created, message, to_user)
            # message.save()
        return message.message_id

    @classmethod
    def get_messages(cls, message_id=None, to_user_id=None, from_user_id=None):
        if message_id:
            try:
                message = DbMessage.query.where(DbMessage.message_id == message_id).gino.first()
                return message
            except NoSuchRowError:
                return None
        elif from_user_id and to_user_id:
            messages = DbMessage.query.where(DbMessage.to_user==to_user_id, DbMessage.from_user==from_user_id).gino.all()
            return messages
        return DbMessage.query.all()

    # def update_message(self):
    #     return DbMessage.query.where(self.message_id).update(message=self.message)

```

thanks.

**Comment by wwwjfy** [comment]
Models in models.py are actually using another Gino instance `db` than the one initialized with app.

When calling the model methods, the uninitialized engine is invoked.

**Comment by horlahlekhon** [comment]
oh! that was a mistake.... but it still gave the same error when i removed it

```python

from app import DevelopmentConfig
from gino.exceptions import NoSuchRowError
from app import db

class DbUser(db.Model):
    __tablename__ = 'users'

    user_id = db.Column(db.Integer, primary_key=True, unique=True)
    first_name  = db.Column(db.String(255))

    @classmethod
    async def save_user(cls, user_id, first_name):
        try:
            user = await DbUser.query.where(DbUser.user_id==user_id).gino.first()
        except NoSuchRowError:
            user = await DbUser.create(user_id=user_id, first_name=first_name)
            # user.save()
        return user

    @classmethod
    async def get_users(cls, user_id=None):
        if user_id:
            try:
                user = DbUser.query.where(DbUser.user_id==user_id).gino.first()
                return user
            except NoSuchRowError:
                return None
        return DbUser.query.all()


class DbMessage(db.Model):
    __tablename__= 'messages'

    message_id = db.Column(db.Integer,  primary_key=True, unique=True)
    from_user = db.Column(db.String(255))
    ts_created = db.Column(db.DateTime, nullable=False)
    chat = db.Column(db.Integer, db.ForeignKey('users.user_id', ondelete='CASCADE'), nullable=False)
    message = db.Column(db.Text)
    to_user = db.Column(db.Integer, db.ForeignKey('users.user_id', ondelete='CASCADE'))

    def __init__(self, message_id, from_user, ts_created, message, to_user):
        self.message_id = message_id
        self.from_user = from_user
        self.message = message
        self.ts_created = ts_created
        self.to_user = to_user

    def save(self):
        """
            save the new Message model into the database and commit the change
        """
        db.session.add(self)
        db.session.commit()
        return self.id

    @classmethod
    def save_message(cls, message_id, from_user, ts_created, message, to_user):
        try:
            message = DbMessage.query.where(DbMessage.message_id==message_id).gino.first()
            message.message = message
            # message.save()
        except NoSuchRowError:
            message = DbMessage.create(message_id, from_user, ts_created, message, to_user)
            # message.save()
        return message.message_id

    @classmethod
    def get_messages(cls, message_id=None, to_user_id=None, from_user_id=None):
        if message_id:
            try:
                message = DbMessage.query.where(DbMessage.message_id == message_id).gino.first()
                return message
            except NoSuchRowError:
                return None
        elif from_user_id and to_user_id:
            messages = DbMessage.query.where(DbMessage.to_user==to_user_id, DbMessage.from_user==from_user_id).gino.all()
            return messages
        return DbMessage.query.all()

    # def update_message(self):
    #     return DbMessage.query.where(self.message_id).update(message=self.message)




```

**Comment by wwwjfy** [comment]
This is a bit complex, so I made a small test as similar as yours.
I suspect some code may mess the "threadlocal" context.
I'd suggest to get a workable version first and build up the whole system step by step to find the culprit.

```python
from quart import Quart
from gino.ext.quart import Gino

app = Quart(__name__)
app.config.from_object({
    'DB_HOST': 'localhost',
    'DB_DATABASE': 'postgres',
})
db = Gino(app)


@app.route('/')
async def route():
    print((await DbUser.hello()).id)
    return ''


class DbUser(db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer())

    @classmethod
    async def hello(cls):
        return await cls.query.gino.first()


app.run()
```

**Comment by horlahlekhon** [comment]
This works when i run this single file .

**Comment by wwwjfy** [comment]
Right, so I think the problem is how those files are organized.

**Comment by horlahlekhon** [comment]
maybe, i have tried to reorganise it , but the models are not getting the initailized gino instance, i even put them in the same file as the example you gave

**Comment by wwwjfy** [comment]
Most likely it's because multiple db instances like before, maybe in some other files.
Could try to print `db` to see if it's identical everywhere (the memory address).
If you can get a minimal non-workable version I could help to debug.
Or you can also try to use `db` instead of implicit `Model.query`.

**Comment by horlahlekhon** [comment]
can i use db to make a query ?, how would that look like, the `db` instance doesnt have a query function

**Comment by wwwjfy** [comment]
Like `db.first`, but it won't work either. My bad.
Model.query, Model.get, etc are just convenient methods, and eventually it'll use `db` to execute those queries. As you can see, parent class of models is `db.Model`.

Could you `print(db)` in different files and see if they're the same?

**Comment by horlahlekhon** [comment]
The instances are different :

```
Inside models file MetaData(bind=<gino.api._PlaceHolder object at 0x7fba299aa4f8>)
Inside Request file MetaData(bind=<gino.api._PlaceHolder object at 0x7fba299aa4f8>)
Inside view MetaData(bind=<gino.api._PlaceHolder object at 0x7fba299aa4c8>)
Inside view file MetaData(bind=<gino.api._PlaceHolder object at 0x7fba297888e8>)
Inside app init file MetaData(bind=<gino.api._PlaceHolder object at 0x7fba297888e8>)
Inside app init file MetaData(bind=<gino.api._PlaceHolder object at 0x7fba297888e8>)
```

are they meant to be different.

**Comment by wwwjfy** [comment]
No, in most cases, there should be only one `db` instance. I think that's the problem.
Please try to find where else this db instance is initialized.

**Comment by horlahlekhon** [comment]
There isnt any other place where the db is reinitialized. in fact , it is recreating itself in every file that i imported it.. i.e : 

```
Inside models file MetaData(bind=<gino.api._PlaceHolder object at 0x7fdc7b40c5e8>)
Inside Request file MetaData(bind=<gino.api._PlaceHolder object at 0x7fdc7b814948>)
Inside view file MetaData(bind=<gino.api._PlaceHolder object at 0x7fdc7b1e1798>)

```

**Comment by wwwjfy** [comment]
Now it's more like a Python question 😅
Could you show me the file structure? Because in the first reply, db is initialized in `__init__.py` and later it's imported from `app`

**Comment by horlahlekhon** [comment]
```
.
├── +2348073865242.session
├── +2348073865242.session-journal
├── controller.py
├── __init__.py
├── models.py
├── request.py
└── views.py


```

**Comment by horlahlekhon** [comment]
now , i put all the modules inside one file a, and i still get varying db instances..

i.e

```python

# from app import DevelopmentConfig
from gino.exceptions import NoSuchRowError
# from app import app
from gino.ext.quart import Gino

from config import DevelopmentConfig
from quart import Quart
# from gino.ext.quart import Gino

app = Quart(__name__)

app.config.from_object(DevelopmentConfig)
db = Gino(app=app)


print("Inside models file", db)

class DbUser(db.Model):
    __tablename__ = 'users'

    user_id = db.Column(db.Integer, primary_key=True, unique=True)
    first_name  = db.Column(db.String(255))

    @classmethod
    async def save_user(cls, user_id, first_name):
        try:
            user = await DbUser.query.where(DbUser.user_id==user_id).gino.first()
        except NoSuchRowError:
            user = await DbUser.create(user_id=user_id, first_name=first_name)
            # user.save()
        return user

    @classmethod
    async def get_users(cls, user_id=None):
        if user_id:
            try:
                user = DbUser.query.where(DbUser.user_id==user_id).gino.first()
                return user
            except NoSuchRowError:
                return None
        return DbUser.query.all()


class DbMessage(db.Model):
    __tablename__= 'messages'

    message_id = db.Column(db.Integer,  primary_key=True, unique=True)
    from_user = db.Column(db.String(255))
    ts_created = db.Column(db.DateTime, nullable=False)
    chat = db.Column(db.Integer, db.ForeignKey('users.user_id', ondelete='CASCADE'), nullable=False)
    message = db.Column(db.Text)
    to_user = db.Column(db.Integer, db.ForeignKey('users.user_id', ondelete='CASCADE'))

    def __init__(self, message_id, from_user, ts_created, message, to_user):
        self.message_id = message_id
        self.from_user = from_user
        self.message = message
        self.ts_created = ts_created
        self.to_user = to_user

    def save(self):
        """
            save the new Message model into the database and commit the change
        """
        db.session.add(self)
        db.session.commit()
        return self.id

    @classmethod
    def save_message(cls, message_id, from_user, ts_created, message, to_user):
        try:
            message = DbMessage.query.where(DbMessage.message_id==message_id).gino.first()
            message.message = message
            # message.save()
        except NoSuchRowError:
            message = DbMessage.create(message_id, from_user, ts_created, message, to_user)
            # message.save()
        return message.message_id

    @classmethod
    def get_messages(cls, message_id=None, to_user_id=None, from_user_id=None):
        if message_id:
            try:
                message = DbMessage.query.where(DbMessage.message_id == message_id).gino.first()
                return message
            except NoSuchRowError:
                return None
        elif from_user_id and to_user_id:
            messages = DbMessage.query.where(DbMessage.to_user==to_user_id, DbMessage.from_user==from_user_id).gino.all()
            return messages
        return DbMessage.query.all()

    # def update_message(self):
    #     return DbMessage.query.where(self.message_id).update(message=self.message)


# --------------------------------------------------------------------------------------

from telethon import TelegramClient
from telethon.errors import SessionPasswordNeededError
# from .models import DbUser, DbMessage
from gino.exceptions import NoSuchRowError
from telethon.tl.types import Channel, Chat
# from .models import db

print("Inside Request file", db)
class Connection(TelegramClient):
    def __init__(self, api_hash, api_id, phone):
        super(Connection, self).__init__(session=phone, api_hash=api_hash, api_id=api_id)
        self.phone = phone
        self.me = None

    async def get_code(self):
        return await self.send_code_request(self.phone)

    async def login(self, code=None, password=None):
        await self.connect()
        if not self.is_user_authorized():
            try:
                await self.sign_in(phone=self.phone, code=code)
            except SessionPasswordNeededError:
                await self.sign_in(phone=self.phone, code=code, password=password)
        me = await self.get_me()
        try:
            me = DbUser.get_users(me.id)
        except NoSuchRowError:
            me = DbUser.save_user(user_id=me.id, first_name=me.first_name)
        self.me = me
        return self


    async def messages(self, limit=100):
        dialogs = await self.get_dialogs(limit=limit)
        messages = None
        for dialog in dialogs:
            user = dialog.entity
            if (not isinstance(user, (Channel, Chat))) and user.first_name.find("bot") < 0 and (not user.is_self):
                try:
                    new_user = await DbUser.get_users(user.id)
                except NoSuchRowError:
                    new_user = await DbUser.save_user(user.id, user.first_name)

                messages = await self.get_messages(user, limit=limit)
                for message in messages:
                    try:
                        msg = await DbMessage.get_messages(message_id=message.id)
                        # msg.update_message()
                    except NoSuchRowError:
                        from_user = await DbUser.get_users(user_id=message.from_id)
                        to_user = await DbUser.get_users(user_id=message.to_id.user_id)
                        msg = await DbMessage.save_message(message_id=message.id, from_user=from_user, to_user=to_user, ts_created=message.date, message=message.message)
        return messages





# -----------------------------------------------------------------------------------


# from app import app

from quart import (
    jsonify, request, Blueprint, g, Response,
    session
)
import asyncio
# from .request import Connection
from app.controller import (get_all_messages, get_all_users)
import quart.json as json

deep = Blueprint('telegram', __name__, url_prefix='/telegram')
neutral = Blueprint('retrieve', __name__, url_prefix='/data')


@deep.before_app_first_request
async def start_up():
    global client
    api_hash = session.get("api_hash")
    phone = session.get("phone")
    api_id = session.get("api_id")
    client = Connection(api_hash=api_hash, api_id=api_id, phone=phone)

    await client.connect()


@app.after_serving
async def cleanup():
    await client.disconnect()


@neutral.route('/get-data', strict_slashes=False, methods=['POST'])
async def get_data():
    data = await request.get_json()
    session["api_id"] = data.get("api_id")
    session["api_hash"] = data.get("api_hash")
    session["phone"] = data.get("phone")
    return Response(status=200, response="")


@deep.route('/sign-in', strict_slashes=False, methods=['POST', 'GET'])
async def sign_in():
    data = await request.get_json()
    if not data:
        await client.send_code_request(session.get("phone"))
        resp = json.dumps({"status": "incompleted", "message": "Kindly call this endpoint again with the sms code "})
        return Response(status=200, response=resp)
    await client.sign_in(code=data.get("code"))
    messages = []
    if await client.is_user_authorized():
        dialog = (await client.get_dialogs())[0]

        async for m in client.iter_messages(dialog, 10):
            messages.append(m.to_dict())
    else:
        Response(status=400, response=json.dumps({"status": "failure", "message": "Invalid code"}))
    resp = json.dumps(messages)
    return Response(status=200, response=resp)


@deep.route('/get_messages', strict_slashes=False, methods=['GET'])
async def get_messages():
    """
    get_messages : This returns the list of the messages of the user...
                   This is updated as new as the last time /messages/fetch is called.

    Returns:
        [type] -- [description]
    """
    msgs = json.dumps(client.get_dialogs())
    return Response(status=200, response=msgs)


@deep.route('/who-am-i', strict_slashes=False, methods=['GET'])
async def me():
    """
    me gets the user that is logged in

    Returns:
        json -- The details of the user that is logged in currently
    """
    me = await client.get_me()
    return Response(status=200, response=me.to_json())


@deep.route('/messages/fetch', strict_slashes=False, methods=['GET'])
async def fetch():
    """
        This endpoint is used as an event to trigger message refresh from telegram
        it will pull the messages anytime this is called and save in the database.

        Returns:
            Empty  -- a 200 response status
    """
    msgs = await client.messages(limit=500)
    count = len(msgs)
    return Response(status=200, response="")


@deep.route('/save', strict_slashes=False, methods=['GET'])
async def save():
    """
    me gets the user that is logged in

    Returns:
        json -- The details of the user that is logged in currently
    """
    # data = request.get_json()
    # me = await db.query_executor .save_user(user_id=1235431, first_name='olalekan')
    return Response(status=200, response=me.first_name)


# from .models import db

# print("Inside view file", db)


# ------------------------------------------------------------------------------------------------

# from config import DevelopmentConfig
# from quart import Quart
# # from gino.ext.quart import Gino
#
# app = Quart(__name__)
#
# app.config.from_object(DevelopmentConfig)
# db = Gino(app=app)
# from app.views import deep, neutral

app.register_blueprint(deep)
app.register_blueprint(neutral)

if __name__ == '__main__':
    app.run()




```

and i still get varrying instances in different place in the file
```

Inside models file MetaData(bind=<gino.api._PlaceHolder object at 0x7f435f7158e8>)
Inside Request file MetaData(bind=<gino.api._PlaceHolder object at 0x7f435eb7c4f8>)
Inside models file MetaData(bind=<gino.api._PlaceHolder object at 0x7f435eb7cb58>)
Inside Request file MetaData(bind=<gino.api._PlaceHolder object at 0x7f435eb7cac8>)
Inside view file MetaData(bind=<gino.api._PlaceHolder object at 0x7f435e949a38>)

```

**Comment by wwwjfy** [comment]
Use `print(id(db))` and let's see if it happens.
The address here is the PlaceHolder's, and it's generated every time so they'll be different.

**Comment by horlahlekhon** [comment]
ok... the one in  a single file all have teh same id.

but the ones in different files... returns this 

```
Inside __init__ file 139982673615392
Inside __init__ file 139982673199344
Inside models file 139982673199344
Inside Request file 139982673199344
Inside view file 139982673199344
```

the __init__ file instance is created twice.

**Comment by wwwjfy** [comment]
I guess you can find it out now?

**Comment by horlahlekhon** [comment]
find what out?, the db is not defined twice.... probably the file is reloading ?...
and still the version that i put all the modules inside one file does not still work, i still get the error `Gino engine is not initialized`

**Comment by wwwjfy** [comment]
can you paste init file then, with those print? there should not be reloading unless you ask it to

**Comment by horlahlekhon** [comment]
```python
from config import DevelopmentConfig
from quart import Quart
from gino.ext.quart import Gino

app = Quart(__name__)

app.config.from_object(DevelopmentConfig)
db = Gino(app=app)
print("Inside __init__ file", id(db))
from app.views import deep, neutral

app.register_blueprint(deep)
app.register_blueprint(neutral)

if __name__ == '__main__':
    app.run()




```

**Comment by wwwjfy** [comment]
So print is executed twice. I think it might still be related to the organization of files. For example, `app` here is both a package name and a variable name.
You could add the following around `print` to see who imports this file the second time.
```
import traceback

traceback.print_stack()
```

I suspect either it's imported by others which should not as this is the entry point, or Quart subprocess causing it.

**Comment by horlahlekhon** [comment]
i get this :

```traceback
Inside __init__ file 139878443715048
Inside __init__ file 139878443294960
Inside models file 139878443294960
Inside Request file 139878443294960
Inside view file 139878443294960
Running on http://127.0.0.1:5000 (CTRL + C to quit)
  File "/home/lekan/Documents/workspace/telegram/deepview-telegram/deepview-telegram/app/__init__.py", line 11, in <module>
    from app.views import deep, neutral
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lekan/Documents/workspace/telegram/deepview-telegram/deepview-telegram/app/__init__.py", line 16, in <module>
    traceback.print_stack()
  File "/home/lekan/Documents/workspace/telegram/deepview-telegram/deepview-telegram/app/__init__.py", line 16, in <module>
    traceback.print_stack()


```

**Comment by wwwjfy** [comment]
There may be cyclic imports here.
A few links might be useful:
https://stackoverflow.com/questions/19077381/what-happens-when-a-module-is-imported-twice
https://stackoverflow.com/questions/4798589/what-could-cause-a-python-module-to-be-imported-twice

**Comment by horlahlekhon** [comment]
But i dont have a cyclic import here, if i had, the python interpreter would have flagged import error.
plus even if a package is imported twice am not sure it will create two instances of it. it would just use the first one and churn the second as stated in one of those links.

**Comment by wwwjfy** [comment]
I mean implicit cyclic imports, the two prints suggest so.
I suspect it's how the `db` object is imported in blueprints and/or models.
This is not really a Gino question but a Python question, I don't know how I can help here.
If possible I could take a look if you can get a _minimal_ _non-working_ version.

**Comment by horlahlekhon** [comment]
ok, i will try to try the versions backwardly if i can get a working version. Thanks for your assistance

**Comment by wwwjfy** [comment]
Closing due to inactivity. Feel free to reopen.
