### ISSUE TITLE
Do something about cython (upload bdist wheels to pypi or try staying pure-python)

### ISSUE THREAD

**Issue by AmatanHead** [fantix/gino#60]
Hello! So, there's a cython extension now in GINO. I've noticed that because of this:

```
    Complete output from command python setup.py egg_info:
    zip_safe flag not set; analyzing archive contents...
    
    Installed /tmp/pip-build-9tbfp_79/gino/.eggs/pytest_runner-2.12-py3.6.egg
    Searching for Cython>=0.24
    Reading https://pypi.python.org/simple/Cython/
    Downloading https://pypi.python.org/packages/68/41/2f259b62306268d9cf0d6434b4e83a2fb1785b34cfce27fdeeca3adffd0e/Cython-0.26.1.tar.gz#md5=8853dcb78749a786ad5ccdc007a8932f
    Best match: Cython 0.26.1
    Processing Cython-0.26.1.tar.gz
    Writing /tmp/easy_install-abw0vw8f/Cython-0.26.1/setup.cfg
    Running Cython-0.26.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-abw0vw8f/Cython-0.26.1/egg-dist-tmp-jv4k3ocj
    Unable to find pgen, not compiling formal grammar.
    warning: no files found matching 'Doc/*'
    warning: no files found matching '*.pyx' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Utility'
    /tmp/easy_install-abw0vw8f/Cython-0.26.1/Cython/Plex/Scanners.c:4:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    Traceback (most recent call last):
      File "/usr/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
        extra_postargs)
      File "/usr/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/usr/lib/python3.6/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/usr/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    ... and so on ....
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-9tbfp_79/gino/
```

While this is most likely problem with my environment and not the GINO itself (and, even more, I know how to fix it), the same things may cause other users to suffer. Necessity to build cython extensions complicates deployment because now one have to install gcc, cython, python-dev etc. instead of just doing `pip install gino`.

So I propose making life a little easier by either
* staying pure-python; utilize `asyncpg.protocol.protocol._create_record` for updating records or ask asyncpg's community to implement an official method for updating records;
* upload bdist wheels for various platforms to pypi.

Also, if we choose to use cython than I see no reason why keep other parts of project purely pythonic.

**Comment by fantix** [comment]
Yes you are right. FYI I'm sending a PR to asyncpg to add the `_update_record` in upstream codebase. If that doesn't work, we'll have to find other way out as you said.

**Comment by fantix** [comment]
There might be another way out - using the `RowProxy` from SQLAlchemy. It also requires a bit more code in the `dialect.py` to make the result processors work in the way SQLAlchemy does.

**Comment by fantix** [comment]
Turns out to be working. I'll revert Cython extension stuff in 0.6.0.
