### ISSUE TITLE
Error handling Numeric column

### ISSUE THREAD

**Issue by jonahfang** [fantix/gino#67]
* GINO version: 0.5.1
* Python version: 3.6.2
* Operating System: Ubuntu 14.04

### Description

Error when create table record.

### What I Did

```
--model:
class Worker(db.Model):
    __tablename__ = 'workers'

    id = db.Column(db.BigInteger(), primary_key=True)
    nickname = db.Column(db.Unicode(), default='noname')
    dcount = db.Column(db.Integer(),nullable=True)
    money = db.Column(db.Numeric(12,2),nullable=True)
    added_on = db.Column(db.DateTime(), default=get_now_datetime())
    added_date = db.Column(db.String(10), default=get_now_date_text())

    def __repr__(self):
        return '{}<{}>'.format(self.nickname, self.id)

-- error from code:
    u1 = await Worker.create(nickname='fantix}',dcount=1,money=Decimal('123.12'))
    u2 = await Worker.get(u1.id)

-- error msg:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 503, in handle_request
    response = await response
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 109, in __next__
    return self.gen.send(None)
  File "/src/apps/utils/log.py", line 34, in decorated_function
    return await f(*args, **kwargs)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 109, in __next__
    return self.gen.send(None)
    ...
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 109, in __next__
    return self.gen.send(None)
  File "/usr/local/lib/python3.6/site-packages/gino/crud.py", line 184, in get
    return await cls.__metadata__.first(clause, bind=bind)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 109, in __next__
    return self.gen.send(None)
  File "/usr/local/lib/python3.6/site-packages/gino/api.py", line 207, in first
    conn, clause, *multiparams, **params)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 109, in __next__
    return self.gen.send(None)
  File "/usr/local/lib/python3.6/site-packages/gino/dialect.py", line 240, in do_first
    connection, clause, multiparams, params)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 109, in __next__
    return self.gen.send(None)
  File "/usr/local/lib/python3.6/site-packages/gino/dialect.py", line 226, in _execute_clauseelement
    item = context.process_rows(rows, return_model=return_model)
  File "/usr/local/lib/python3.6/site-packages/gino/dialect.py", line 107, in process_rows
    rv = rows = self.get_result_proxy().process_rows(rows)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 877, in get_result_proxy
    return result.ResultProxy(self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/result.py", line 653, in __init__
    self._init_metadata()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/result.py", line 682, in _init_metadata
    self._metadata = ResultMetaData(self, cursor_description)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/result.py", line 215, in __init__
    num_ctx_cols, cols_are_ordered, textual_ordered)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/result.py", line 379, in _merge_cursor_description
    in enumerate(result_columns)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/result.py", line 378, in <listcomp>
    ) for idx, (key, name, obj, type_)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 840, in get_result_processor
    return type_._cached_result_processor(self.dialect, coltype)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/type_api.py", line 472, in _cached_result_processor
    d[coltype] = rp = d['impl'].result_processor(dialect, coltype)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/sqltypes.py", line 596, in result_processor
    'storage.' % (dialect.name, dialect.driver))
AttributeError: 'AsyncpgDialect' object has no attribute 'driver'

```

**Comment by fantix** [comment]
@jonahfang please verify

**Comment by jonahfang** [comment]
@fantix ,yes, it works now!

**Comment by fantix** [comment]
Good to know! Released 0.5.2 for this one. Sorry for the disturb!

**Comment by jonahfang** [comment]
I have done all tests on gino from my usage case. Thanks for your great work again.

**Comment by fantix** [comment]
You're welcome. Please advice on #59 too if time, do you think it a good idea to hide asyncpg interfaces of pool and connection, and to redesign and unify GINO APIs?
