### ISSUE TITLE
Error: asyncpg.exceptions.TooManyConnectionsError: sorry, too many clients already

### ISSUE THREAD

**Issue by jonahfang** [fantix/gino#70]
* GINO version: 0.5.2
* Python version: 3.6.2
* Operating System: Ununtu 14.04

### Description

I use vegeta to load test.

### What I Did

```
--- to be tested Sanic view:
async def use_postgres1(request):
    d = get_now_datetime()
    u1 = await Worker.create(nickname=f'fantix{d}',dcount=1,money=Decimal('123.12'))
    u2 = await Worker.get(u1.id) 
    return ajax_data({'rid':u2.id,'name':u2.nickname})

--- db server config
    app.config.DB_HOST = DB_CONFIG['host']
    app.config.DB_USER = DB_CONFIG['user']
    app.config.DB_PORT = DB_CONFIG['port']
    app.config.DB_PASSWORD = DB_CONFIG['password']
    app.config.DB_DATABASE = DB_CONFIG['database']
    app.config.DB_POOL_MIN_SIZE = 5
    app.config.DB_POOL_MAX_SIZE = 10000
 
--- load test script:
[I] $echo "GET http://dserver:8023/demo/d0401" | vegeta attack -rate=200 -duration=5s | vegeta report -output t24.html -reporter plot

--- error message:
[2017-09-11 Mon 00:51:35.145][fusion2_api_min.local]Exception occured in one of response middleware handlers
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 527, in handle_request
    response)
  File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 660, in _run_response_middleware
    _response = await _response
  File "/usr/local/lib/python3.6/site-packages/gino-0.5.2-py3.6.egg/gino/ext/sanic.py", line 85, in on_response
    await ctx.__aexit__(None, None, None)
  File "/usr/local/lib/python3.6/site-packages/gino-0.5.2-py3.6.egg/gino/pool.py", line 122, in __aexit__
    await self.pool.release(con)
  File "/usr/local/lib/python3.6/site-packages/gino-0.5.2-py3.6.egg/gino/pool.py", line 193, in release
    return await connection.release(close=True)
  File "/usr/local/lib/python3.6/site-packages/gino-0.5.2-py3.6.egg/gino/pool.py", line 70, in release
    conn_to_release = await fut
  File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 503, in handle_request
    response = await response
  File "/opt/app/apps/utils/log.py", line 34, in decorated_function
    return await f(*args, **kwargs)
  File "/opt/app/apps/demo/views/gino.py", line 38, in use_postgres1
    u1 = await Worker.create(nickname=f'中文fantix{d}',dcount=1,money=Decimal('123.12'))
  File "/usr/local/lib/python3.6/site-packages/gino-0.5.2-py3.6.egg/gino/crud.py", line 162, in create
    row = await cls.__metadata__.first(q, bind=bind)
  File "/usr/local/lib/python3.6/site-packages/gino-0.5.2-py3.6.egg/gino/api.py", line 207, in first
    conn, clause, *multiparams, **params)
  File "/usr/local/lib/python3.6/site-packages/gino-0.5.2-py3.6.egg/gino/dialect.py", line 242, in do_first
    connection, clause, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/gino-0.5.2-py3.6.egg/gino/dialect.py", line 224, in _execute_clauseelement
    prepared = await context.prepare()
  File "/usr/local/lib/python3.6/site-packages/gino-0.5.2-py3.6.egg/gino/dialect.py", line 117, in prepare
    return await self.connection.prepare(self.statement)
  File "/usr/local/lib/python3.6/site-packages/gino-0.5.2-py3.6.egg/gino/dialect.py", line 61, in prepare
    rv = self._stmt = await self._conn.prepare(statement)
  File "/usr/local/lib/python3.6/site-packages/gino-0.5.2-py3.6.egg/gino/pool.py", line 89, in wrapper
    conn = await self.get_connection()
  File "/usr/local/lib/python3.6/site-packages/gino-0.5.2-py3.6.egg/gino/pool.py", line 57, in get_connection
    self._conn = await self._conn_task
  File "/usr/local/lib/python3.6/site-packages/asyncpg/pool.py", line 453, in _acquire
    return await _acquire_impl()
  File "/usr/local/lib/python3.6/site-packages/asyncpg/pool.py", line 444, in _acquire_impl
    proxy = await ch.acquire()  # type: PoolConnectionProxy
  File "/usr/local/lib/python3.6/site-packages/asyncpg/pool.py", line 147, in acquire
    await self.connect()
  File "/usr/local/lib/python3.6/site-packages/asyncpg/pool.py", line 138, in connect
    connection_class=self._pool._connection_class)
  File "/usr/local/lib/python3.6/site-packages/asyncpg/connect_utils.py", line 274, in _connect_addr
    await asyncio.wait_for(connected, loop=loop, timeout=timeout)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
asyncpg.exceptions.TooManyConnectionsError: sorry, too many clients already

```

**Comment by fantix** [comment]
This is no surprise. Please note this error comes from PostgreSQL, who normally limits 100 maximum concurrent connections by default. It is usually meaningless to have an application DB pool larger than the server's limit, even when pgBouncer is used (bounced majorly for multiple application servers, it doesn't increase the maximum concurrent transaction number) .

**Comment by jonahfang** [comment]
在高并发的情况下，如何发挥出Sanic+gino(asyncpg)的优势呢？

**Comment by fantix** [comment]
首先要说的是，PostgreSQL 在充分调优的前提下，其性能仅与硬件资源有关系。只要舍得砸钱，PostgreSQL 是可以支撑很大的压力的。而最大连接数就是体现其性能的一项指标，连接不见得是越多越好，因为每个连接都是有内存消耗的，连接越多，可用于缓存的内存就越少，性能反而会受影响。数据库连接数与并发是有一个平衡点的。

其次，asyncpg 在性能方面的优势在于其原生的实现方式，而不在于异步。异步只能让它更慢，而不是更快，可以参考 SQLAlchemy 作者的[这篇博客](http://techspot.zzzeek.org/2015/02/15/asynchronous-python-and-databases/)。

最后您提到高并发，我认为，Sanic + asyncpg 的性能优势在于，可以在更少地占用硬件资源的情况下，处理更多的 I/O 集中的操作，比如直接管理网络接入质量较差的客户端、大量 WebSocket、频繁调用不稳定第三方服务、等待设计好的数据库锁（需要精心设计！）、处理数据库异步通知等，并同时可以保持一个统一的开发环境（全异步）以提升开发效率（而非执行效率）。而对于“瞬时”的 CRUD 操作，asyncpg 并没有优势，而 GINO 则更是增加了性能开销，以换取开发效率。而且，异步的数据库访问会带来使用上的风险，除了精心设计的数据库锁，应尽量避免在数据库事务当中 `await` 任何非数据库的操作，使数据库访问尽早结束，否则容易引起数据库锁的雪球效应。

总之我觉得 Sanic + GINO 的定位是高端玩家快速开发的场景，优势在于开发效率，而在榨取数据库性能方面同常规手段无异，asyncpg 并不比传统方法更有效，除了目前其底层实现尚有执行速度优势。

**Comment by jonahfang** [comment]
受教，谢谢！

**Comment by fantix** [comment]
表客气。

**Comment by fantix** [comment]
For English, please follow up to https://groups.google.com/forum/#!topic/sqlalchemy/Amy5QrcefgQ
